name: Full backend lifecycle workflow

on:
  workflow_dispatch:

jobs:
  Ecr-build-push-wf:
    permissions:
      id-token: write
      contents: read
      
    uses: org-548/reusable/.github/workflows/workflow.yaml@main
    with:
      app_unit: server
      ecr-repo-name: server-repo
      values-file: backend-values.yaml
    secrets:
      github_pat: ${{ secrets.PA_TOKEN }}
          
