name: Destroy

on:
  workflow_dispatch

jobs:
  first:
    name: first-job
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423489195:role/${{ vars.OIDC_ROLE_NAME }}
          aws-region: eu-north-1

      - name: Git Setup
        shell: bash
        run: |
          echo "Git setup"
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'  

      - name: Check and clone repository
        shell: bash
        run: |
          echo "Clone repo"
          if grep -q infra <<< $(ls -lt); then
            echo "Repository with name infra already exists!"
            rm -rf infra
          fi
          git clone git@github.com:org-548/infra.git

      - name: Terraform destroy
        working-directory: infra/terraform
        run: |
          terraform init
          terraform destroy --auto-approve

      - name: Down cloudformation stack
        run: aws cloudformation delete-stack --stack-name ${{ vars.CFN_STACK_NAME }}

        
