name: Build an upload ECR image

on: [workflow_dispatch]

jobs:
  first:
    name: first-job
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423489195:role/role-for-github-oidc
          aws-region: eu-north-1

      - name: Git Setup  
        shell: bash
        run: |
          echo "Git setup"
          pwd
          git config --global user.name 'Tereza'
          git config --global user.email 'bisharyant@gmail.com'  

      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Check and clone repository
        shell: bash
        #working-directory: ${{ inputs.not-default-workdir }}
        run: |
          echo "Clone repo"
          pwd
          if grep -q infra <<< $(ls -lt); then
            echo "Repository with name infra already exists!"
            rm -rf infra
          fi
          git clone git@github.com:org-548/infra.git

      - name: Check newly cloned repo    
        run: |
          pwd
          ls -lah
          ls -lah ./infra

      - name: Create ECR resources with terraform
        id: get-output
        working-directory: infra/terraform
        continue-on-error: true
        run: |
          terraform init
          #terraform destroy --auto-approve -var-file=./values/server.tfvars
          terraform plan -var-file=./values/server.tfvars
          terraform apply --auto-approve -var-file=./values/server.tfvars | tail -n 11 >> out.txt
          echo "error-out=$(head -n 1 out.txt)" >> $GITHUB_OUTPUT

      - name: Reapply terraform code
        working-directory: infra/terraform
        if: contains("${{ steps.get-output.outputs.error-out}}", 'Not enough list items')
        run: |
          terraform apply --auto-approve -var-file=./values/server.tfvars

      - name: Logit to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build, tag and push image to AWS ECR
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: server-repo
          IMAGE_TAG: ${{ env.SHORT_SHA }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Setup Helmwave
        run: |
          export VERSION=0.19.3
          wget -c https://github.com/helmwave/helmwave/releases/download/v$VERSION/helmwave_${VERSION}_linux_amd64.tar.gz -O - | tar -xz
          mv helmwave /usr/local/bin/

      - name: Helmwave build/up
        working-directory: infra/charts
        run: |
          helmwave up --build --kubedog
          

    
