name: ECR build-push in source repo

on: [workflow_dispatch]

jobs:
  Using-first-reusable-workflow:
  
    permissions:
      id-token: write
      contents: read
      
    uses: org-548/reusable/.github/workflows/ecr-build-push.yaml@main
    with:
      app_unit: server
      ecr-repo-name: server-repo
      values-file: srv-values.yaml
    secrets:
      #region: ${{ secrets.AWS_REGION }}
      github_pat: ${{ secrets.PA_TOKEN }}

  Using-second-reusable-workflow:

    permissions:
      id-token: write
      contents: read
  
    needs: Using-first-reusable-workflow
    uses: org-548/reusable/.github/workflows/k8s-deployment.yaml@main
    secrets:
      github_pat: ${{ secrets.PA_TOKEN }}
      #region: ${{ secrets.AWS_REGION }}

  Trigger-frontend-workflow:
    needs: Using-second-reusable-workflow
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in frontend repo
        run: |
          # Set the required variables
          repo_owner="org-548" 
          repo_name="client"  
          event_type="trigger-workflow"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PA_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"    
